# From "Thinking in C++, 2nd Edition, Volume 1, 
# Annotated Solutions Guide" by Chuck Allison
# At http://www.BruceEckel.com
# (c)2001 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\S07
# Invoke with: make

CPP = bcc32
OFLAGS = -c
EXEFLAG = -e
OBJEXT = obj
.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(OFLAGS) $<
.cpp.exe :
	$(CPP) $< $(EXEFLAG)$@

Borland:  \
	DefaultArgs.exe \
	ManyArgs.exe \
	Message.exe \
	MessageWithPrefix.exe \
	NamelessArg.exe \
	Text.exe

Microsoft:  \
	DefaultArgs.exe \
	ManyArgs.exe \
	Message.exe \
	MessageWithPrefix.exe \
	NamelessArg.exe \
	Text.exe

g++295:  \
	DefaultArgs.exe \
	ManyArgs.exe \
	Message.exe \
	MessageWithPrefix.exe \
	NamelessArg.exe \
	Text.exe

g++3:  \
	DefaultArgs.exe \
	ManyArgs.exe \
	Message.exe \
	MessageWithPrefix.exe \
	NamelessArg.exe \
	Text.exe

edg:  \
	DefaultArgs.exe \
	ManyArgs.exe \
	Message.exe \
	MessageWithPrefix.exe \
	NamelessArg.exe \
	Text.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


DefaultArgs.exe: DefaultArgs.cpp

ManyArgs.exe: ManyArgs.cpp

Message.exe: Message.cpp

MessageWithPrefix.exe: MessageWithPrefix.cpp

NamelessArg.exe: NamelessArg.cpp

Text.exe: Text.cpp

