# From "Thinking in C++, 2nd Edition, Volume 1, 
# Annotated Solutions Guide" by Chuck Allison
# At http://www.BruceEckel.com
# (c)2001 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\S09
# Invoke with: make

CPP = bcc32
OFLAGS = -c
EXEFLAG = -e
OBJEXT = obj
.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(OFLAGS) $<
.cpp.exe :
	$(CPP) $< $(EXEFLAG)$@

Borland:  \
	CharArray.$(OBJEXT) \
	ColorAndHue.exe \
	Exercise7.exe \
	FieldAccessors.exe \
	FixMacroSideEffects.exe \
	InternalLinkage.$(OBJEXT) \
	LinkError.exe \
	MemberObject.exe \
	TrackTime.exe \
	UseDEBUG.exe \
	UseTRACE.exe

Microsoft:  \
	CharArray.$(OBJEXT) \
	ColorAndHue.exe \
	Exercise7.exe \
	FieldAccessors.exe \
	FixMacroSideEffects.exe \
	InternalLinkage.$(OBJEXT) \
	LinkError.exe \
	MemberObject.exe \
	TrackTime.exe \
	UseDEBUG.exe \
	UseTRACE.exe

g++295:  \
	CharArray.$(OBJEXT) \
	ColorAndHue.exe \
	Exercise7.exe \
	FieldAccessors.exe \
	FixMacroSideEffects.exe \
	InternalLinkage.$(OBJEXT) \
	LinkError.exe \
	MemberObject.exe \
	TrackTime.exe \
	UseDEBUG.exe \
	UseTRACE.exe

g++3:  \
	CharArray.$(OBJEXT) \
	ColorAndHue.exe \
	Exercise7.exe \
	FieldAccessors.exe \
	FixMacroSideEffects.exe \
	InternalLinkage.$(OBJEXT) \
	LinkError.exe \
	MemberObject.exe \
	TrackTime.exe \
	UseDEBUG.exe \
	UseTRACE.exe

edg:  \
	CharArray.$(OBJEXT) \
	ColorAndHue.exe \
	Exercise7.exe \
	FieldAccessors.exe \
	FixMacroSideEffects.exe \
	InternalLinkage.$(OBJEXT) \
	LinkError.exe \
	MemberObject.exe \
	TrackTime.exe \
	UseDEBUG.exe \
	UseTRACE.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


CharArray.$(OBJEXT): CharArray.cpp

ColorAndHue.exe: ColorAndHue.cpp

Exercise7.exe: CharArray.$(OBJEXT) Exercise7.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Exercise7.exe Exercise7.$(OBJEXT) CharArray.$(OBJEXT)

Exercise7.$(OBJEXT): Exercise7.cpp
FieldAccessors.exe: FieldAccessors.cpp

FixMacroSideEffects.exe: FixMacroSideEffects.cpp

InternalLinkage.$(OBJEXT): InternalLinkage.cpp

LinkError.exe: LinkError.cpp
	@echo compile and link LinkError.cpp by hand


MemberObject.exe: MemberObject.cpp

TrackTime.exe: TrackTime.cpp

UseDEBUG.exe: UseDEBUG.cpp

UseTRACE.exe: UseTRACE.cpp

