# Master makefile for "Thinking in C++, 2nd Edition, 
# Volume 1, Annotated Solutions Guide" by Chuck Allison
# at http://www.BruceEckel.com
# (c)2001 MindView Inc. Copyright notice in Copyright.txt
# Compiles all the code in the book

help: 
	@echo To compile all programs from 
	@echo "Thinking in C++, 2nd Edition, Volume 1, Annotated Solutions Guide"
	@echo type one of the following commands, according to your platform:
	@echo make borland
	@echo 'make g++295 (g++ 2.95, used with Cygwin)'
	@echo make g++3
	@echo make edg
	@echo make microsoft



borland: 
	cd S02
	make borland
	cd ..
	cd S03
	make borland
	cd ..
	cd S04
	make borland
	cd ..
	cd S05
	make borland
	cd ..
	cd S06
	make borland
	cd ..
	cd S07
	make borland
	cd ..
	cd S08
	make borland
	cd ..
	cd S09
	make borland
	cd ..
	cd S10
	make borland
	cd ..
	cd S11
	make borland
	cd ..
	cd S12
	make borland
	cd ..
	cd S13
	make borland
	cd ..
	cd S14
	make borland
	cd ..
	cd S15
	make borland
	cd ..
	cd S16
	make borland
	cd ..


g++295: 
	cd S02; make g++295 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S03; make g++295 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S04; make g++295 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S05; make g++295 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S06; make g++295 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S07; make g++295 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S08; make g++295 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S09; make g++295 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S10; make g++295 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S11; make g++295 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S12; make g++295 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S13; make g++295 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S14; make g++295 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S15; make g++295 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S16; make g++295 CPP=g++ EXEFLAG=-o OBJEXT=o


g++3: 
	cd S02; make g++3 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S03; make g++3 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S04; make g++3 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S05; make g++3 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S06; make g++3 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S07; make g++3 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S08; make g++3 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S09; make g++3 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S10; make g++3 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S11; make g++3 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S12; make g++3 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S13; make g++3 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S14; make g++3 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S15; make g++3 CPP=g++ EXEFLAG=-o OBJEXT=o
	cd S16; make g++3 CPP=g++ EXEFLAG=-o OBJEXT=o


edg: 
	cd S02
	make edg CPP='$(SXLCMD) \dinkum\sxl\lib\sxl.lib' EXEFLAG=-o OBJEXT=o
	cd ..
	cd S03
	make edg CPP='$(SXLCMD) \dinkum\sxl\lib\sxl.lib' EXEFLAG=-o OBJEXT=o
	cd ..
	cd S04
	make edg CPP='$(SXLCMD) \dinkum\sxl\lib\sxl.lib' EXEFLAG=-o OBJEXT=o
	cd ..
	cd S05
	make edg CPP='$(SXLCMD) \dinkum\sxl\lib\sxl.lib' EXEFLAG=-o OBJEXT=o
	cd ..
	cd S06
	make edg CPP='$(SXLCMD) \dinkum\sxl\lib\sxl.lib' EXEFLAG=-o OBJEXT=o
	cd ..
	cd S07
	make edg CPP='$(SXLCMD) \dinkum\sxl\lib\sxl.lib' EXEFLAG=-o OBJEXT=o
	cd ..
	cd S08
	make edg CPP='$(SXLCMD) \dinkum\sxl\lib\sxl.lib' EXEFLAG=-o OBJEXT=o
	cd ..
	cd S09
	make edg CPP='$(SXLCMD) \dinkum\sxl\lib\sxl.lib' EXEFLAG=-o OBJEXT=o
	cd ..
	cd S10
	make edg CPP='$(SXLCMD) \dinkum\sxl\lib\sxl.lib' EXEFLAG=-o OBJEXT=o
	cd ..
	cd S11
	make edg CPP='$(SXLCMD) \dinkum\sxl\lib\sxl.lib' EXEFLAG=-o OBJEXT=o
	cd ..
	cd S12
	make edg CPP='$(SXLCMD) \dinkum\sxl\lib\sxl.lib' EXEFLAG=-o OBJEXT=o
	cd ..
	cd S13
	make edg CPP='$(SXLCMD) \dinkum\sxl\lib\sxl.lib' EXEFLAG=-o OBJEXT=o
	cd ..
	cd S14
	make edg CPP='$(SXLCMD) \dinkum\sxl\lib\sxl.lib' EXEFLAG=-o OBJEXT=o
	cd ..
	cd S15
	make edg CPP='$(SXLCMD) \dinkum\sxl\lib\sxl.lib' EXEFLAG=-o OBJEXT=o
	cd ..
	cd S16
	make edg CPP='$(SXLCMD) \dinkum\sxl\lib\sxl.lib' EXEFLAG=-o OBJEXT=o
	cd ..


microsoft: 
	cd S02
	make microsoft CPP='cl -GX -GR"" -Dfor="if(0);else for"' EXEFLAG=-Fe OBJEXT=obj
	cd ..
	cd S03
	make microsoft CPP='cl -GX -GR"" -Dfor="if(0);else for"' EXEFLAG=-Fe OBJEXT=obj
	cd ..
	cd S04
	make microsoft CPP='cl -GX -GR"" -Dfor="if(0);else for"' EXEFLAG=-Fe OBJEXT=obj
	cd ..
	cd S05
	make microsoft CPP='cl -GX -GR"" -Dfor="if(0);else for"' EXEFLAG=-Fe OBJEXT=obj
	cd ..
	cd S06
	make microsoft CPP='cl -GX -GR"" -Dfor="if(0);else for"' EXEFLAG=-Fe OBJEXT=obj
	cd ..
	cd S07
	make microsoft CPP='cl -GX -GR"" -Dfor="if(0);else for"' EXEFLAG=-Fe OBJEXT=obj
	cd ..
	cd S08
	make microsoft CPP='cl -GX -GR"" -Dfor="if(0);else for"' EXEFLAG=-Fe OBJEXT=obj
	cd ..
	cd S09
	make microsoft CPP='cl -GX -GR"" -Dfor="if(0);else for"' EXEFLAG=-Fe OBJEXT=obj
	cd ..
	cd S10
	make microsoft CPP='cl -GX -GR"" -Dfor="if(0);else for"' EXEFLAG=-Fe OBJEXT=obj
	cd ..
	cd S11
	make microsoft CPP='cl -GX -GR"" -Dfor="if(0);else for"' EXEFLAG=-Fe OBJEXT=obj
	cd ..
	cd S12
	make microsoft CPP='cl -GX -GR"" -Dfor="if(0);else for"' EXEFLAG=-Fe OBJEXT=obj
	cd ..
	cd S13
	make microsoft CPP='cl -GX -GR"" -Dfor="if(0);else for"' EXEFLAG=-Fe OBJEXT=obj
	cd ..
	cd S14
	make microsoft CPP='cl -GX -GR"" -Dfor="if(0);else for"' EXEFLAG=-Fe OBJEXT=obj
	cd ..
	cd S15
	make microsoft CPP='cl -GX -GR"" -Dfor="if(0);else for"' EXEFLAG=-Fe OBJEXT=obj
	cd ..
	cd S16
	make microsoft CPP='cl -GX -GR"" -Dfor="if(0);else for"' EXEFLAG=-Fe OBJEXT=obj
	cd ..


clean: 
	cd S02
	del *.obj
	del *.exe
	del *.tds
	cd ..
	cd S03
	del *.obj
	del *.exe
	del *.tds
	cd ..
	cd S04
	del *.obj
	del *.exe
	del *.tds
	cd ..
	cd S05
	del *.obj
	del *.exe
	del *.tds
	cd ..
	cd S06
	del *.obj
	del *.exe
	del *.tds
	cd ..
	cd S07
	del *.obj
	del *.exe
	del *.tds
	cd ..
	cd S08
	del *.obj
	del *.exe
	del *.tds
	cd ..
	cd S09
	del *.obj
	del *.exe
	del *.tds
	cd ..
	cd S10
	del *.obj
	del *.exe
	del *.tds
	cd ..
	cd S11
	del *.obj
	del *.exe
	del *.tds
	cd ..
	cd S12
	del *.obj
	del *.exe
	del *.tds
	cd ..
	cd S13
	del *.obj
	del *.exe
	del *.tds
	cd ..
	cd S14
	del *.obj
	del *.exe
	del *.tds
	cd ..
	cd S15
	del *.obj
	del *.exe
	del *.tds
	cd ..
	cd S16
	del *.obj
	del *.exe
	del *.tds
	cd ..


cleanLinux: 
	cd S02; rm -f *.o; rm -f *.exe
	cd S03; rm -f *.o; rm -f *.exe
	cd S04; rm -f *.o; rm -f *.exe
	cd S05; rm -f *.o; rm -f *.exe
	cd S06; rm -f *.o; rm -f *.exe
	cd S07; rm -f *.o; rm -f *.exe
	cd S08; rm -f *.o; rm -f *.exe
	cd S09; rm -f *.o; rm -f *.exe
	cd S10; rm -f *.o; rm -f *.exe
	cd S11; rm -f *.o; rm -f *.exe
	cd S12; rm -f *.o; rm -f *.exe
	cd S13; rm -f *.o; rm -f *.exe
	cd S14; rm -f *.o; rm -f *.exe
	cd S15; rm -f *.o; rm -f *.exe
	cd S16; rm -f *.o; rm -f *.exe
