# From "Thinking in C++, 2nd Edition, Volume 1, 
# Annotated Solutions Guide" by Chuck Allison
# At http://www.BruceEckel.com
# (c)2001 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\S11
# Invoke with: make

CPP = bcc32
OFLAGS = -c
EXEFLAG = -e
OBJEXT = obj
.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(OFLAGS) $<
.cpp.exe :
	$(CPP) $< $(EXEFLAG)$@

Borland:  \
	AutoCopy.exe \
	CallByRef.exe \
	ExtraArgs.exe \
	MemPtr.exe \
	PointerToMemArray.exe \
	RefToTemp.exe \
	ShallowCopy.exe \
	TraceCopies.exe

Microsoft:  \
	AutoCopy.exe \
	CallByRef.exe \
	ExtraArgs.exe \
	MemPtr.exe \
	PointerToMemArray.exe \
	RefToTemp.exe \
	ShallowCopy.exe \
	TraceCopies.exe

g++295:  \
	AutoCopy.exe \
	CallByRef.exe \
	ExtraArgs.exe \
	MemPtr.exe \
	PointerToMemArray.exe \
	RefToTemp.exe \
	ShallowCopy.exe \
	TraceCopies.exe

g++3:  \
	AutoCopy.exe \
	CallByRef.exe \
	ExtraArgs.exe \
	MemPtr.exe \
	PointerToMemArray.exe \
	RefToTemp.exe \
	ShallowCopy.exe \
	TraceCopies.exe

edg:  \
	AutoCopy.exe \
	CallByRef.exe \
	ExtraArgs.exe \
	MemPtr.exe \
	PointerToMemArray.exe \
	RefToTemp.exe \
	ShallowCopy.exe \
	TraceCopies.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


AutoCopy.exe: AutoCopy.cpp

CallByRef.exe: CallByRef.cpp

ExtraArgs.exe: ExtraArgs.cpp

MemPtr.exe: MemPtr.cpp

PointerToMemArray.exe: PointerToMemArray.cpp

RefToTemp.exe: RefToTemp.cpp
	@echo compile RefToTemp.cpp by hand


ShallowCopy.exe: ShallowCopy.cpp

TraceCopies.exe: TraceCopies.cpp

