# From "Thinking in C++, 2nd Edition, Volume 1, 
# Annotated Solutions Guide" by Chuck Allison
# At http://www.BruceEckel.com
# (c)2001 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\S15
# Invoke with: make

CPP = bcc32
OFLAGS = -c
EXEFLAG = -e
OBJEXT = obj
.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(OFLAGS) $<
.cpp.exe :
	$(CPP) $< $(EXEFLAG)$@

Borland:  \
	AllMyRodents.exe \
	InheritVirtuals.exe \
	Instrument4.exe \
	PolymorphicSizeof.exe \
	PolymorphicWhatAmI.exe \
	SliceTheBase.exe \
	VirtualClone.exe \
	VirtualHit.exe

Microsoft:  \
	AllMyRodents.exe \
	InheritVirtuals.exe \
	Instrument4.exe \
	PolymorphicSizeof.exe \
	PolymorphicWhatAmI.exe \
	SliceTheBase.exe \
	VirtualHit.exe

g++295:  \
	AllMyRodents.exe \
	InheritVirtuals.exe \
	Instrument4.exe \
	PolymorphicSizeof.exe \
	PolymorphicWhatAmI.exe \
	SliceTheBase.exe \
	VirtualClone.exe \
	VirtualHit.exe

g++3:  \
	AllMyRodents.exe \
	InheritVirtuals.exe \
	Instrument4.exe \
	PolymorphicSizeof.exe \
	PolymorphicWhatAmI.exe \
	SliceTheBase.exe \
	VirtualClone.exe \
	VirtualHit.exe

edg:  \
	AllMyRodents.exe \
	InheritVirtuals.exe \
	Instrument4.exe \
	PolymorphicSizeof.exe \
	PolymorphicWhatAmI.exe \
	SliceTheBase.exe \
	VirtualClone.exe \
	VirtualHit.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


AllMyRodents.exe: AllMyRodents.cpp

InheritVirtuals.exe: InheritVirtuals.cpp

Instrument4.exe: Instrument4.cpp

PolymorphicSizeof.exe: PolymorphicSizeof.cpp

PolymorphicWhatAmI.exe: PolymorphicWhatAmI.cpp

SliceTheBase.exe: SliceTheBase.cpp

VirtualClone.exe: VirtualClone.cpp

VirtualHit.exe: VirtualHit.cpp

