# From "Thinking in C++, 2nd Edition, Volume 1, 
# Annotated Solutions Guide" by Chuck Allison
# At http://www.BruceEckel.com
# (c)2001 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\S04
# Invoke with: make

CPP = bcc32
OFLAGS = -c
EXEFLAG = -e
OBJEXT = obj
.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(OFLAGS) $<
.cpp.exe :
	$(CPP) $< $(EXEFLAG)$@

Borland:  \
	Exercise3.exe \
	GetSet.exe \
	LinkedList.exe \
	MyStruct.$(OBJEXT) \
	Nested.exe \
	Sizeof.exe \
	Storage.exe \
	StringCopy.exe \
	StructSize.exe \
	UsesThis.exe

Microsoft:  \
	Exercise3.exe \
	GetSet.exe \
	LinkedList.exe \
	MyStruct.$(OBJEXT) \
	Nested.exe \
	Sizeof.exe \
	Storage.exe \
	StringCopy.exe \
	StructSize.exe \
	UsesThis.exe

g++295:  \
	Exercise3.exe \
	GetSet.exe \
	LinkedList.exe \
	MyStruct.$(OBJEXT) \
	Nested.exe \
	Sizeof.exe \
	Storage.exe \
	StringCopy.exe \
	StructSize.exe \
	UsesThis.exe

g++3:  \
	Exercise3.exe \
	GetSet.exe \
	LinkedList.exe \
	MyStruct.$(OBJEXT) \
	Nested.exe \
	Sizeof.exe \
	Storage.exe \
	StringCopy.exe \
	StructSize.exe \
	UsesThis.exe

edg:  \
	Exercise3.exe \
	GetSet.exe \
	LinkedList.exe \
	MyStruct.$(OBJEXT) \
	Nested.exe \
	Sizeof.exe \
	Storage.exe \
	StringCopy.exe \
	StructSize.exe \
	UsesThis.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


Exercise3.exe: MyStruct.$(OBJEXT) Exercise3.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Exercise3.exe Exercise3.$(OBJEXT) MyStruct.$(OBJEXT)

Exercise3.$(OBJEXT): Exercise3.cpp
GetSet.exe: GetSet.cpp

LinkedList.exe: LinkedList.cpp

MyStruct.$(OBJEXT): MyStruct.cpp

Nested.exe: Nested.cpp

Sizeof.exe: Sizeof.cpp

Storage.exe: Storage.cpp

StringCopy.exe: StringCopy.cpp

StructSize.exe: StructSize.cpp

UsesThis.exe: UsesThis.cpp

