# From "Thinking in C++, 2nd Edition, Volume 1, 
# Annotated Solutions Guide" by Chuck Allison
# At http://www.BruceEckel.com
# (c)2001 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\S08
# Invoke with: make

CPP = bcc32
OFLAGS = -c
EXEFLAG = -e
OBJEXT = obj
.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(OFLAGS) $<
.cpp.exe :
	$(CPP) $< $(EXEFLAG)$@

Borland:  \
	ConstReference.exe \
	ConstTime.exe \
	ConstTime.exe \
	GlobalConst.exe \
	InitList.exe \
	Quoter.$(OBJEXT) \
	StringLiteral.exe \
	Volatile.exe

Microsoft:  \
	ConstReference.exe \
	ConstTime.exe \
	ConstTime.exe \
	GlobalConst.exe \
	InitList.exe \
	Quoter.$(OBJEXT) \
	StringLiteral.exe \
	Volatile.exe

g++295:  \
	ConstReference.exe \
	ConstTime.exe \
	ConstTime.exe \
	GlobalConst.exe \
	InitList.exe \
	Quoter.$(OBJEXT) \
	StringLiteral.exe \
	Volatile.exe

g++3:  \
	ConstReference.exe \
	ConstTime.exe \
	ConstTime.exe \
	GlobalConst.exe \
	InitList.exe \
	Quoter.$(OBJEXT) \
	StringLiteral.exe \
	Volatile.exe

edg:  \
	ConstReference.exe \
	ConstTime.exe \
	ConstTime.exe \
	GlobalConst.exe \
	InitList.exe \
	Quoter.$(OBJEXT) \
	StringLiteral.exe \
	Volatile.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


ConstReference.exe: ConstReference.cpp

ConstTime.exe: ConstTime.cpp

ConstTime.exe: ConstTime.cpp

GlobalConst.exe: GlobalConst.cpp

InitList.exe: InitList.cpp

Quoter.$(OBJEXT): Quoter.cpp

StringLiteral.exe: StringLiteral.cpp

Volatile.exe: Volatile.cpp

