# From "Thinking in C++, 2nd Edition, Volume 1, 
# Annotated Solutions Guide" by Chuck Allison
# At http://www.BruceEckel.com
# (c)2001 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\S14
# Invoke with: make

CPP = bcc32
OFLAGS = -c
EXEFLAG = -e
OBJEXT = obj
.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(OFLAGS) $<
.cpp.exe :
	$(CPP) $< $(EXEFLAG)$@

Borland:  \
	BusinessTraveler.exe \
	DefaultConstruction.exe \
	HierarchyConstruction.exe \
	InaccessibleBase.exe \
	LikeARock.exe \
	NarrowingCast.exe \
	Proxy.exe \
	StaticBaseMethods.exe \
	StringVector.exe

Microsoft:  \
	BusinessTraveler.exe \
	DefaultConstruction.exe \
	HierarchyConstruction.exe \
	InaccessibleBase.exe \
	LikeARock.exe \
	NarrowingCast.exe \
	Proxy.exe \
	StaticBaseMethods.exe

g++295:  \
	BusinessTraveler.exe \
	DefaultConstruction.exe \
	HierarchyConstruction.exe \
	InaccessibleBase.exe \
	LikeARock.exe \
	NarrowingCast.exe \
	Proxy.exe \
	StaticBaseMethods.exe \
	StringVector.exe

g++3:  \
	BusinessTraveler.exe \
	DefaultConstruction.exe \
	HierarchyConstruction.exe \
	InaccessibleBase.exe \
	LikeARock.exe \
	NarrowingCast.exe \
	Proxy.exe \
	StaticBaseMethods.exe \
	StringVector.exe

edg:  \
	BusinessTraveler.exe \
	DefaultConstruction.exe \
	HierarchyConstruction.exe \
	InaccessibleBase.exe \
	LikeARock.exe \
	NarrowingCast.exe \
	Proxy.exe \
	StaticBaseMethods.exe \
	StringVector.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


BusinessTraveler.exe: BusinessTraveler.cpp

DefaultConstruction.exe: DefaultConstruction.cpp

HierarchyConstruction.exe: HierarchyConstruction.cpp

InaccessibleBase.exe: InaccessibleBase.cpp
	@echo Compile InaccessibleBase.cpp by hand!


LikeARock.exe: LikeARock.cpp

NarrowingCast.exe: NarrowingCast.cpp
	@echo Compile NarrowingCast.cpp by hand!


Proxy.exe: Proxy.cpp

StaticBaseMethods.exe: StaticBaseMethods.cpp

StringVector.exe: StringVector.cpp

