# From "Thinking in C++, 2nd Edition, Volume 1, 
# Annotated Solutions Guide" by Chuck Allison
# At http://www.BruceEckel.com
# (c)2001 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\S13
# Invoke with: make

CPP = bcc32
OFLAGS = -c
EXEFLAG = -e
OBJEXT = obj
.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(OFLAGS) $<
.cpp.exe :
	$(CPP) $< $(EXEFLAG)$@

Borland:  \
	ClassHeap.exe \
	Counted.exe \
	CountedVector.exe \
	MappedMemory.exe \
	PlacementNew.exe \
	WrongDelete.exe \
	WrongPointer.exe

Microsoft:  \
	ClassHeap.exe \
	Counted.exe \
	CountedVector.exe \
	MappedMemory.exe \
	PlacementNew.exe \
	WrongDelete.exe \
	WrongPointer.exe

g++295:  \
	ClassHeap.exe \
	Counted.exe \
	CountedVector.exe \
	MappedMemory.exe \
	PlacementNew.exe \
	WrongDelete.exe \
	WrongPointer.exe

g++3:  \
	ClassHeap.exe \
	Counted.exe \
	CountedVector.exe \
	MappedMemory.exe \
	PlacementNew.exe \
	WrongDelete.exe \
	WrongPointer.exe

edg:  \
	ClassHeap.exe \
	Counted.exe \
	CountedVector.exe \
	MappedMemory.exe \
	PlacementNew.exe \
	WrongDelete.exe \
	WrongPointer.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


ClassHeap.exe: ClassHeap.cpp

Counted.exe: Counted.cpp

CountedVector.exe: CountedVector.cpp

MappedMemory.exe: MappedMemory.cpp

PlacementNew.exe: PlacementNew.cpp

WrongDelete.exe: WrongDelete.cpp

WrongPointer.exe: WrongPointer.cpp

